name: "Maester Action"
description: "Monitor your Microsoft 365 tenant's security configuration using Maester, THE PowerShell-based test automation framework."
branding:
  icon: "check-circle"
  color: "red"
inputs:
  tenant_id:
    description: "Entra ID Tenant ID"
    required: true
  client_id:
    description: "App Registration Client ID"
    required: true
  include_public_tests:
    description: "Include public test repository 'maester365/maester-tests' as well as private tests in the test run"
    required: false
    default: "true"
  mail_recipients:
    description: "A list of email addresses to send the test results to. Please separate multiple email addresses with a comma."
    required: false
    default: ""
  mail_userid:
    description: "The user id of the sender of the mail. This is required since the action is using application permissions."
    required: false
    default: ""
  mail_testresultsuri:
    description: "Uri to the detailed test results page."
    required: false
    default: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  include_tags:
    description: "A list of tags to include in the test run. Please separate multiple tags with a comma (without space)."
    required: false
    default: ""
  exclude_tags:
    description: "A list of tags to exclude from the test run. Please separate multiple tags with a comma (without space)."
    required: false
    default: ""
  pester_verbosity:
    description: "Pester verbosity level. Options: 'None', 'Normal', 'Detailed', 'Diagnostic'"
    required: false
    default: "None"
  step_summary:
    type: boolean
    description: "Define whether a summary is outputted to GitHub Actions."
    required: false
    default: true
  artifact_upload:
    type: boolean
    description: "Define whether the results are uploaded as Artifacts."
    required: false
    default: true
  install_prerelease:
    type: boolean
    description: "Installs the preview version, allowing access to new cmdlets."
    required: false
    default: false
  include_exchange:
    type: boolean
    description: "Include Exchange Online tests in the test run."
    required: false
    default: false
  include_teams:
    type: boolean
    description: "Include Teams tests in the test run."
    required: false
    default: true
  disable_telemetry:
    type: boolean
    description: "If set, telemetry information will not be logged."
    required: false
    default: false
  notification_teams_webhook:
    description: "Webhook URL for sending test results to Teams."
    required: false
    default: ""
  notification_teams_channel_id:
    description: "The ID of the Teams channel to send the test results to."
    required: false
    default: ""
  notification_teams_team_id:
    description: "The ID of the Teams team to send the test results to."
    required: false
    default: ""

outputs:
  results_json:
    description: "The file location of the JSON output of the test results."
    value: ${{ steps.maester.outputs.results_json }}


runs:
  using: "composite"
  steps:
    - name: 🕑 Set current date as env variable
      shell: bash
      run: echo "NOW=$(date +'%Y-%m-%d-T%H%M%S')" >> $GITHUB_ENV

    - name: 🧑‍💻 Checkout latest public tests
      if: ${{ inputs.include_public_tests == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: maester365/maester-tests
        path: public-tests

    - name: 🧑‍💻 Checkout latest private tests
      uses: actions/checkout@v4
      with:
        path: private-tests

    - name: 🔑 Sign in to Entra ID
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        allow-no-subscriptions: true

    - name: 🧪 Run Maester
      id: maester
      shell: pwsh
      run: |
        . ${{ github.action_path }}\action\Get-MtAccessTokenUsingCli.ps1
        ${{ github.action_path }}\action\Run-Maester.ps1 -TenantId '${{ inputs.tenant_id}}' `
          -ClientId '${{ inputs.client_id }}' `
          -Path '${{ github.workspace }}' `
          -MailRecipients '${{ inputs.mail_recipients }}' `
          -MailUser '${{ inputs.mail_userid }}' `
          -TestResultURI '${{ inputs.mail_testresultsuri }}' `
          -IncludeTags '${{ inputs.include_tags }}' `
          -ExcludeTags '${{ inputs.exclude_tags }}' `
          -PesterVerbosity '${{ inputs.pester_verbosity }}' `
          -GitHubStepSummary ('${{ inputs.step_summary }}' -eq 'true') `
          -Preview ('${{ inputs.install_prerelease }}' -eq 'true') `
          -IncludeExchange ('${{ inputs.include_exchange }}' -eq 'true') `
          -IncludeTeams ('${{ inputs.include_teams }}' -eq 'true') `
          -DisableTelemetry ('${{ inputs.disable_telemetry}}' -eq 'true') `
          -TeamsWebhookUri '${{ inputs.notification_teams_webhook }}' `
          -TeamsChannelId '${{ inputs.notification_teams_channel_id }}' `
          -TeamsTeamId '${{ inputs.notification_teams_team_id }}'

    - name: 📃 Archive Maester Html Report
      uses: actions/upload-artifact@v4
      if: ${{ inputs.artifact_upload == 'true' }}
      with:
        name: maester-test-results-${{ env.NOW }}
        path: test-results
        include-hidden-files: true
