name: Create PowerShell module release artifact

on:
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Get current module version
        id: moduleversion
        shell: pwsh
        run: |
          $ManfifestPath = "$($ModuleRoot)/Maester.psd1"
          $CurrentVersion = Import-PowerShellDataFile $ManfifestPath | Select-Object -ExpandProperty ModuleVersion
          Add-Content -Path $env:GITHUB_OUTPUT -Value "newtag=$CurrentVersion"

      - name: Commit updated manifest file to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.updatemodule.outputs.newtag }}

      - name: Create PowerShell module package
        id: module-creation
        shell: pwsh
        run: |
          Compress-Archive -Path ./powershell/* -DestinationPath ./maester.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "maester.zip"
          replacesArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: legacy
          prerelease: false
          tag: ${{ steps.moduleversion.outputs.newtag }}
          commit: ${{ github.sha }}
