# Run pester tests
name: build-validation

on:
  workflow_dispatch:
  workflow_call:

  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pwshmodule:
              - 'powershell/**'

      - name: Install PowerShell dependencies
        if: steps.filter.outputs.pwshmodule == 'true'
        shell: pwsh
        run: |
          Install-Module PSFramework -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module PSModuleDevelopment -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module Microsoft.Graph.Authentication -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber

      - name: Install PowerShell dependencies (Windows PowerShell)
        if: runner.os == 'Windows' && steps.filter.outputs.pwshmodule == 'true'
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module PSModuleDevelopment -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
          Install-Module Microsoft.Graph.Authentication -Force -SkipPublisherCheck -Scope CurrentUser -AllowClobber

      - name: Run Pester tests
        if: steps.filter.outputs.pwshmodule == 'true'
        shell: pwsh
        run: |
          ./powershell/tests/pester.ps1

      - name: Run Tests using Windows PowerShell
        if: runner.os == 'Windows' && steps.filter.outputs.pwshmodule == 'true'
        shell: powershell
        run: |
          # Remove old test results
          Remove-Item -Path TestResults -Recurse -Force -ErrorAction SilentlyContinue
          # Run Pester tests on Windows PowerShell
          ./powershell/tests/pester.ps1

      - name: Publish Pester test results
        uses: dorny/test-reporter@v1
        if: always() && steps.filter.outputs.pwshmodule == 'true'
        with:
          name: Maester Test Results (${{ runner.os }}/PowerShell)
          path: TestResults/*.xml
          reporter: java-junit
          fail-on-error: true
