name: Update PowerShell module manifest

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Update PowerShell module version and manifest file
        id: updatemodule
        shell: pwsh
        run: |
          & ./.github/workflows/minor-version-update.ps1

      - name: Commit updated manifest file to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.updatemodule.outputs.newtag }}
